let s1="Nani Pasupuleti ";
console.log(s1);
console.log(typeof(s1));
console.log(`${s1} is a good boy`);
console.log(s1.length);
console.log(s1.substring(1,6));
console.log(s1.charAt(2));
console.log(s1.indexOf('f'));
let s2=" RAmesh";
console.log(s1.concat(s2));
console.log(s1.toUpperCase());
console.log(s2.toLowerCase());